version: '3'
services:
  mongo:
    container_name: mongoDb5
    image: mongo:5.0.26
    stdin_open: true
    tty: true
    restart: always
    volumes: 
      - ./:/code
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: funnyVideos
      

  backend:
    build: .
    restart: always
    container_name: funnyVideosBackend
    ports:
      - 3001:3001
    environment:
      # app
      - NODE_ENV=development
      - APP_NAME=funnyVideos-backend-service
      - PORT=3001
    env_file:
      - .env
    depends_on:
      - mongo